### ISSUE TITLE
Add `meta` attribute set to packages

### ISSUE THREAD

**Issue by FedericoSchonborn** [FedericoSchonborn/budgie-overlay#2]
https://nixos.org/manual/nixpkgs/unstable/#chap-meta

- [x] `budgie-backgrounds`
- [x] `budgie-control-center`
- [x] `budgie-desktop`
- [x] `budgie-desktop-view`
- [x] `budgie-screensaver`
- [x] `budgie-trash-applet`
